### PR TITLE
Add patches from 3.10.1 to 3.14.0 to list

### PR DESCRIPTION
**Pull request by torstehu**

### CODE REVIEW

**Comment by torstehu** [comment]
A most gentle ping here

**Comment by torstehu** [comment]
Whoops, I think merging this may have broken a large portion of the site, http://aligulac.com/misc/days/ , http://aligulac.com/misc/balance/ and the player profiles all return HTTP error 500.

**Comment by TheBB** [comment]
No, that's not your fault.

**Comment by TheBB** [comment]
Should be up again now. Sometimes the database temp files blow up. :-)

**Pull request merged**
